# -*- coding: utf-8 -*-
"""BI_2. Univariate Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uD7r-wcYC3XUFSCqwmE7vIMpDMBGRUiw
"""



"""# UNIVARIATE ANALYSIS
# Dataset: advanced_business_management_dataset(1).csv
# Purpose: Analyze One Variable at a Time
"""

# 1. Import Libraries
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 3. Load Dataset
# ============================================================

df = pd.read_csv("https://raw.githubusercontent.com/baren-kumar/Exploratory-Data-Analysis-EDA-/refs/heads/main/advanced_business_management_dataset.csv")

# 4. Show Dataset
# ============================================================

print("Dataset Shape:", df.shape)
display(df.head())

# 5. Select One Variable
# Example Variable = Net_Sales
# ============================================================

sales = df["Net_Sales"]

# 6. Mean Calculation
# Formula:
# Mean = Sum of Values / Number of Values
# ============================================================

mean_value = sales.mean()

print("Mean of Net Sales:")
print(mean_value)

# 7. Median Calculation
# Formula:
# Median = Middle value after sorting
# ============================================================

median_value = sales.median()

print("\nMedian of Net Sales:")
print(median_value)

# 8. Mode Calculation
# Formula:
# Mode = Most frequent value

# ============================================================

mode_value = sales.mode()

print("\nMode of Net Sales:")
print(mode_value)

# 9. Standard Deviation
# Formula:
# Standard Deviation = Spread of data from mean
# ============================================================

std_value = sales.std()

print("\nStandard Deviation of Net Sales:")
print(std_value)

# 10. Variance
# Formula:
# Variance = Average squared deviation from mean
# ============================================================

variance_value = sales.var()

print("\nVariance of Net Sales:")
print(variance_value)

# 11. Frequency Distribution
# ============================================================

frequency_distribution = sales.value_counts()

print("\nFrequency Distribution:")
display(frequency_distribution)

# 12. Statistical Summary
# ============================================================

summary = pd.DataFrame({
    "Metric": [
        "Mean",
        "Median",
        "Mode",
        "Standard Deviation",
        "Variance",
        "Minimum",
        "Maximum"
    ],
    "Value": [
        mean_value,
        median_value,
        mode_value.iloc[0],
        std_value,
        variance_value,
        sales.min(),
        sales.max()
    ]
})

print("\nStatistical Summary:")
display(summary)

# 13. HISTOGRAM
# Distribution of Net Sales
# ============================================================

plt.figure(figsize=(10,5))

plt.hist(sales,
         bins=20)

plt.title("Histogram of Net Sales")
plt.xlabel("Net Sales")
plt.ylabel("Frequency")

plt.show()

# 14. BOX PLOT
# ============================================================

plt.figure(figsize=(8,5))

plt.boxplot(sales)

plt.title("Box Plot of Net Sales")

plt.ylabel("Net Sales")

plt.show()

# 15. DENSITY PLOT
# ============================================================

plt.figure(figsize=(10,5))

sales.plot(kind='density')

plt.title("Density Plot of Net Sales")

plt.xlabel("Net Sales")

plt.grid(True)

plt.show()

# 16. Monthly Sales Distribution
# ============================================================

df["Date"] = pd.to_datetime(df["Date"])

df["Month"] = df["Date"].dt.to_period("M").astype(str)

monthly_sales = df.groupby("Month")["Net_Sales"].sum()

print("\nMonthly Sales Distribution:")
display(monthly_sales)

plt.figure(figsize=(12,5))

plt.bar(monthly_sales.index,
        monthly_sales.values)

plt.title("Monthly Sales Distribution")

plt.xlabel("Month")

plt.ylabel("Net Sales")

plt.xticks(rotation=45)

plt.show()

# 17. Average Customer Age Example
# ============================================================

# If customer age column exists:
# Uncomment below code

# average_age = df["Customer_Age"].mean()
# print("Average Customer Age:", average_age)

# ============================================================
# 18. Save Summary to Excel
# ============================================================

summary.to_excel("Univariate_Analysis_Summary.xlsx",
                 index=False)

print("\nExcel File Saved Successfully!")

# 19. Download Excel File
# ============================================================

from google.colab import files
files.download("Univariate_Analysis_Summary.xlsx")

# ============================================================
# END OF PROGRAM
# ============================================================

print("\nUnivariate Analysis Completed Successfully!")



